### PR TITLE
Imported `Operation` type from fast-json-patch

### PR DESCRIPTION
**Pull request by jonahbron**
This changes the return type of `generate()` to use the `Operation` type from fast-json-patch, since this project depends on that one. It also uses that `Operation` type for the `observe` callback.

### CODE REVIEW

**Comment by alshakero** [comment]
It's getting hard to track with this number of PRs. Can you please merge them all in 1 PR?

**Comment by jonahbron** [comment]
@alshakero I've started by splitting each change into a separate PR so you can select what you think is appropriate to merge, as these are all largely unrelated changes.  It might be easiest for you to simply merge the ones you like, and close the rest.

However if you wish to unilaterally accept any changes I propose, I'm happy to merge these all together for you.  lmk 😃

**Comment by jonahbron** [comment]
@alshakero Checking in on this.  Have you decided if you want them merged all together, or do you want to maintain the ability to pick-and-choose?

**Comment by alshakero** [comment]
Thank you so much for all the PRs!

**Pull request merged**
