### PR TITLE
Export JSONPatcherProxy as ES Module,

### PR DESCRIPTION
**Pull request by tomalec**
adjust tests to use ES Modules

requires `npm link fast-json-patch` to https://github.com/Starcounter-Jack/JSON-Patch/pull/232

### CODE REVIEW

**Comment by warpech** [comment]
I will review tomorrow. Already we can see that Travis config needs to be updated.

**Comment by tomalec** [comment]
Travis fixed https://travis-ci.org/Palindrom/JSONPatcherProxy/builds/575272306
(GH-Travis integration has some performance problems today)

**Comment by tomalec** [comment]
The last Travis build to check is at https://travis-ci.org/Palindrom/JSONPatcherProxy/builds/575272306, I have no idea why the last commit is not visible here (https://github.com/Palindrom/JSONPatcherProxy/commit/6e72454c59c9a313f73d157641fdf95bb1af3dc5).

**Comment by warpech** [comment]
It seems to me that both GitHub and Travis has lost track of the `module` branch. GitHub says that there is no PR for that branch and advises to start a new PR. Strange, but I will do that to unconfuse them.

**Pull request merged**
